### ISSUE TITLE
utros can be obtained without real downloading anything

### ISSUE THREAD

**Issue by NodesCrew** [stratosnet/sds#122]
Due to the fact that ozone cannot be paid, I noticed one interesting thing.

If i make download requests when there is not enough ozone, i can earn utros. As an example - wallet st1k8svw3fd54eh8jtwj6rpnazjfnak3v7d97gqvm

I took balance measurements and got their change:

mature utros: 117038119 -> 118630158 = -1592039 diff
immature utros: 1592039 -> 1589509 = 2530 diff

BTW ppd logs:
`[INFO]2022/03/03 19:26:55 query_file_info.go:153: failed to download， not enough ozone to process (Available: 29839617 Required: 81926175)`

traffic_dump.log:
`"traffic_info":{"traffic_inbound":1572,"traffic_outbound":1557`

**Comment by NodesCrew** [comment]
Some users reports:

![image](https://user-images.githubusercontent.com/1828306/156636132-91df11b9-dd2f-42c5-aed7-11273c3c7404.jpeg)

**Comment by NodesCrew** [comment]
@alexstratos Perhaps I was unclear and therefore conducted a pure experiment. Steps to reproduce:

0. install ppd
1. ```ppd config```
-- P2PAddress: stsdsp2p17t27wynjhlc2f4xppzfqazchtv376f0nu74rr3
-- WalletAddress: st1nqtlc4et2cxlaz3dpkza0ru550xe9dexw9ugcp

2. Sent 5000000000ustos to st1nqtlc4et2cxlaz3dpkza0ru550xe9dexw9ugcp, txid: 655EA06765891CC57396944B314727EBE2CB3600BDBD3AD7391D4EF0ED615455
3. Run ```ppd start``` in screen
4. Run ```ppd terminal``` in screen

> registerpeer
> activate (txid: 9C6055F9E162E2549C20BC9035E0C0811301ABFF3CF1FCD57B1003B9A5F8E05B, time is 2022/03/04 00:18:54)

Check rewards at https://rest-tropos.thestratos.org/pot/rewards/wallet/st1nqtlc4et2cxlaz3dpkza0ru550xe9dexw9ugcp

```
{"height":"49149","result":{
  "WalletAddress": "st1nqtlc4et2cxlaz3dpkza0ru550xe9dexw9ugcp",
  "MatureTotalReward": [],
  "ImmatureTotalReward": []
}}
```

Check rewards at https://rest-tropos.thestratos.org/pot/rewards/wallet/st1nqtlc4et2cxlaz3dpkza0ru550xe9dexw9ugcp
```
{"height":"49186","result":{
  "WalletAddress": "st1nqtlc4et2cxlaz3dpkza0ru550xe9dexw9ugcp",
  "MatureTotalReward": [],
  "ImmatureTotalReward": [
    {
      "denom": "ustos",
      "amount": "358"
    },
    {
      "denom": "utros",
      "amount": "1207273"
    }
  ]
}}
```


Why did I receive utros?
- I didn't download anything
- I didn't upload anything

**Comment by alexstratos** [comment]
That's expected behavior with current code logic, and your reward amount come from staking(which is aligned with mainnet logic) instead of traffic reward. 

However, the current meta node allow node stay inactive for 2 days(mainnet setup) until meta node will notify chain to suspend the staking reward. This make sense in mainnet since staking STOS on mainnet will have real value. however this bring loophole to abuse the mechanism on testnet. we are making a fix on meta node to massively shorten this inactive period. 

Thanks for reporting this issue. 

If you don't have question, I will close this issue for now.

**Comment by NodesCrew** [comment]
Thank you for paying attention to my question.
I don't mind to close this issue )
